extern const GeoLayout grun_cap_wing_Wing_Cap_Switch_opt1[];
extern const GeoLayout grun_cap_wing_Wing_Cap_Switch_opt2[];
extern const GeoLayout grun_cap_wing_Wing_Cap_Switch_opt3[];
extern const GeoLayout grun_cap_wing_geo[];
extern Lights1 grun_cap_wing_Emblem__EMBLEM__lights;
extern Lights1 grun_cap_wing_Cap__CAP__lights;
extern Lights1 grun_cap_wing_Metal__METAL__lights;
extern u8 grun_cap_wing_Metal_Shade_rgba16_rgba16[];
extern u8 grun_cap_wing_Metal_Light_rgba16_rgba16[];
extern u8 grun_cap_wing_wing_2_rgba16[];
extern u8 grun_cap_wing_wing1_rgba16[];
extern Vtx grun_cap_wing_Wing_Cap_mesh_layer_1_vtx_0[18];
extern Gfx grun_cap_wing_Wing_Cap_mesh_layer_1_tri_0[];
extern Vtx grun_cap_wing_Wing_Cap_mesh_layer_1_vtx_1[118];
extern Gfx grun_cap_wing_Wing_Cap_mesh_layer_1_tri_1[];
extern Vtx grun_cap_wing_Wings_mesh_layer_4_vtx_0[8];
extern Gfx grun_cap_wing_Wings_mesh_layer_4_tri_0[];
extern Vtx grun_cap_wing_Wings_mesh_layer_4_vtx_1[8];
extern Gfx grun_cap_wing_Wings_mesh_layer_4_tri_1[];
extern Gfx mat_grun_cap_wing_Emblem__EMBLEM_[];
extern Gfx mat_grun_cap_wing_Cap__CAP_[];
extern Gfx mat_grun_cap_wing_Metal__METAL_[];
extern Gfx mat_revert_grun_cap_wing_Metal__METAL_[];
extern Gfx mat_grun_cap_wing_Wing_Tip[];
extern Gfx mat_revert_grun_cap_wing_Wing_Tip[];
extern Gfx mat_grun_cap_wing_Wing_Base[];
extern Gfx mat_revert_grun_cap_wing_Wing_Base[];
extern Gfx grun_cap_wing_Wing_Cap_mesh_layer_1[];
extern Gfx grun_cap_wing_Wing_Cap_mesh_layer_1_mat_override_Metal__METAL__0[];
extern Gfx grun_cap_wing_Wings_mesh_layer_4[];
extern Gfx grun_cap_wing_Wings_mesh_layer_4_mat_override_Metal__METAL__0[];
extern Gfx grun_cap_wing_material_revert_render_settings[];
