extern const GeoLayout grun_cap_Normal_Cap_State_Switch_opt1[];
extern const GeoLayout grun_cap_Normal_Cap_State_Switch_opt2[];
extern const GeoLayout grun_cap_Normal_Cap_State_Switch_opt3[];
extern const GeoLayout grun_cap_geo[];
extern Lights1 grun_cap_Emblem__EMBLEM__lights;
extern Lights1 grun_cap_Cap__CAP__lights;
extern Lights1 grun_cap_Metal__METAL__lights;
extern u8 grun_cap_Metal_Shade_rgba16_rgba16[];
extern u8 grun_cap_Metal_Light_rgba16_rgba16[];
extern Vtx grun_cap_Normal_Cap_DL_mesh_layer_1_vtx_0[18];
extern Gfx grun_cap_Normal_Cap_DL_mesh_layer_1_tri_0[];
extern Vtx grun_cap_Normal_Cap_DL_mesh_layer_1_vtx_1[118];
extern Gfx grun_cap_Normal_Cap_DL_mesh_layer_1_tri_1[];
extern Gfx mat_grun_cap_Emblem__EMBLEM_[];
extern Gfx mat_grun_cap_Cap__CAP_[];
extern Gfx mat_grun_cap_Metal__METAL_[];
extern Gfx mat_revert_grun_cap_Metal__METAL_[];
extern Gfx grun_cap_Normal_Cap_DL_mesh_layer_1[];
extern Gfx grun_cap_Normal_Cap_DL_mesh_layer_1_mat_override_Metal__METAL__0[];
extern Gfx grun_cap_material_revert_render_settings[];
